### ISSUE TITLE
Activate logging

### ISSUE THREAD

**Issue by cdupont** [Waziup/Socialbackend#1]
Can we activate logging with wildfly?
Now there is no trace if I do a GET for instance.

**Comment by pandaconstantin** [comment]
Are you sure  your  POST succeed ?

**Comment by cdupont** [comment]
The POST is logged/traced on the server side:
```
18:15:07,097 INFO  [org.waziup.socialbackend.core.Socials] (default task-50) Message delivered by gilbikelenter to PandaConstantin
```
But when I do a GET, I don't see any trace.
It would be nice to have a trace for each requests.

**Comment by pandaconstantin** [comment]
ok , I'm adding it.

**Comment by pandaconstantin** [comment]
Done

**Comment by pandaconstantin** [comment]
Done !

**Comment by cdupont** [comment]
closing
