### ISSUE TITLE
Include the domain

### ISSUE THREAD

**Issue by cdupont** [Waziup/Socialbackend#9]
All waziup API contains the "domain" (see D3.1 for more details):

/api/v1/domain/waziup/sensors

The domain here is "waziup". Another example is "UGB-Farm1". A domain corresponds to a set of resources that we don't want to mix with others.
For instance, we store the sensor measured values in a mongo DB, with collectionName = domain.
So it makes sense to sort the social messages by domain, too...

**Comment by cdupont** [comment]
I suggest to change the API URL to:
```
/domain/:domain/socials
```
And to use the domain for the collection name in mongo.
What do you think?

**Comment by pandaconstantin** [comment]
Ok, let me update then.

**Comment by cdupont** [comment]
Hi Constantin, did you succeed?

**Comment by pandaconstantin** [comment]
Yes I did :)

**Comment by cdupont** [comment]
Thanks, closing
